repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        exclude: '^.+coverage$'
    -   id: trailing-whitespace
    -   id: check-yaml

- repo: https://github.com/google/go-jsonnet
  rev: v0.20.0
  hooks:
    - id: jsonnet-format
    - id: jsonnet-lint

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
