project:
  title: Pelage
  type: website
  output-dir: _site

execute:
  freeze: auto

format:
  html:
    page-layout: full
    theme: [zephyr, shiny-docs.css]
    toc: true
    code-block-border-left: true
    highlight-style: breezedark

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "Pelage: Defensive analysis for Polars"
  description: "Pelage documentation website"
  page-navigation: true
  navbar:
    pinned: true
    left:
      - text: Get started
        file: index.html
      - text: API Reference
        file: reference/index.html
      - text: Examples
        file: notebooks/examples.html
      - text: Coming from dbt
        file: notebooks/coming_from_dbt.html
    right:
      - icon: git
        href: https://github.com/alixtc/pelage/
        text: Git


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pelage
  title: API Reference

  # write sidebar data to this file
  sidebar: _sidebar.yml
  renderer:
    style: _renderer.py
    show_signature_annotations: false
  sections:
    - title: Check functions
      desc: List of check functions.
      package: pelage
      contents:
      - has_columns
      - has_dtypes
      - has_no_nulls
      - has_no_infs
      - unique
      - unique_combination_of_columns
      - accepted_values
      - not_accepted_values
      - accepted_range
      - maintains_relationships
      - column_is_within_n_std
      - custom_check
    - title: Checks with group_by
      package: pelage
      desc: List of check functions with optional `group_by` option.
      contents:
      - has_shape
      - at_least_one
      - not_constant
      - not_null_proportion
      - has_mandatory_values
      - mutually_exclusive_ranges
      - is_monotonic
    - title: Exceptions
      desc: Types aliases and custom exceptions
      package: pelage
      contents:
        - PolarsAssertError
